# Server
server:
  port: 8080
  tomcat:
    accept-count: 1000
  servlet:
    context-path: /computer-components-admin-api/

# Spring
spring:
  application:
    name: Computer-Components-Admin
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  messages:
    basename: messages
    encoding: UTF-8
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: "yyyy-MM-dd HH:mm:ss"
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qap_store
    username: root
    password: Quanganh1792
    driverClassName: com.mysql.cj.jdbc.Driver
  #send mail config
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    port: 587
    username: abc
    password: abc
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.office365.com
      ssl.enable: false
    test-connection: false
    default-param:
      banner-image-url:
      mail-image-url:
      line-image-url:
      logo-image-url:
      company: Cửa hàng QAP Store
      address: Hà Nội
      phoneNumber: 0528 541 357
      email: contact@qapstore.com

jwt:
  prefix: Bearer
  secret: acComputercomponentadmin@2024
  refreshSecret: rfacComputercomponentadmin@2024
  validity: 86400

upload:
  folder: C:\DoAn\image\
